### ISSUE TITLE
i think it breaks the size of the sticker after refreshing with ajax (sammy)

### ISSUE THREAD

**Issue by tim99-1977** [cmiscm/stickerjs#5]

**Comment by uliworm** [comment]
I think it doesnt not depend on ajax, but i still didnt find it.
My Image is 180px * 180px, but the Script converts it to 54px. I have to setup at 480px in the CSS now to see the full size. But then the hover functionality doesnt work smoth any more.

My css:
```css
.sticker {position: relative; width: 480px; height: 480px; margin: 50px;}
.mySticker1 .sticker-img {background-image: url(../pics/fun/geister.jpg);}
```
My Html/Js:
```javascript
<div class="sticker mySticker1"></div>

<script type="text/javascript" src="js/sticker.min.js"></script>
<script type='text/javascript'>
$(document).ready(function () {
	Sticker.init('.sticker');
});
</script>
```

Testpage:
http://www.prinzessin-sally.de/#Fun_Gluehbirne
(at the bottom)

I guess this plugin is not supported any more, but maybe someone knows what i'm doing wrong...
